name: example
description: "A simple example app for simple_storage"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  simple_storage:
    git:
      url: https://github.com/Mahmoud-Saeed-Mahmoud/simple_storage
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
